name: viewport
description: A MediaQuery alternative for Flutter which provides and allows different configurations.
version: 0.1.0-nullsafety.0
homepage: https://github.com/nyarian/viewport

environment:
  sdk: ">=2.12.0-133.2.beta <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  matcher: 0.12.10-nullsafety.3
